# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0003_store_item_request_date_of_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_item_request',
            name='date_of_request',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
