# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import userPortal.models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortal', '0007_child_screentime_is_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='blocks',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[userPortal.models.validate_blocks]),
        ),
        migrations.AlterField(
            model_name='child',
            name='dollars',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, validators=[userPortal.models.validate_dollars]),
        ),
        migrations.AlterField(
            model_name='child',
            name='minutes_left',
            field=models.PositiveSmallIntegerField(blank=True, default=120, validators=[userPortal.models.validate_minutes_left]),
        ),
    ]
