# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortal', '0013_auto_20160824_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRequirementsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_read', models.CharField(help_text="Today's book", max_length=50)),
                ('last_page_read', models.IntegerField(help_text='# of last full page')),
                ('reading_summary', models.CharField(help_text='Reading summary', max_length=100)),
                ('had_schoolwork', models.BooleanField(help_text='Did assigned schoolwork')),
                ('had_other_homework', models.BooleanField(help_text='Did self-directed study')),
                ('homework_description', models.CharField(help_text='Homework summary', max_length=100)),
                ('ixl_math_completed', models.IntegerField(help_text='# IXL math skills today')),
                ('ixl_language_arts_completed', models.IntegerField(help_text='# IXL language arts skills today')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
