# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortal', '0016_auto_20160825_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='most_recent_screentime_ready',
            field=models.DateField(blank=True, null=True),
        ),
    ]
