# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortal', '0017_child_most_recent_screentime_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrequirementsreport',
            name='homework_description',
            field=models.CharField(max_length=100, verbose_name='Homework summary'),
        ),
    ]
