# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortal', '0020_child_child_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrequirementsreport',
            name='ixl_language_arts_completed',
            field=models.IntegerField(verbose_name='Number of IXL language arts skills today'),
        ),
    ]
