# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 00:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userPortal', '0002_auto_20160816_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL),
        ),
    ]
