# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import userPortal.models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortal', '0003_auto_20160816_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='coins',
            field=models.PositiveSmallIntegerField(default=0, validators=[userPortal.models.validate_coins]),
        ),
        migrations.AddField(
            model_name='child',
            name='did_do_homework',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='child',
            name='did_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='child',
            name='dollars',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[userPortal.models.validate_dollars]),
        ),
        migrations.AddField(
            model_name='child',
            name='is_ready_for_screens',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='child',
            name='minutes_left',
            field=models.PositiveSmallIntegerField(default=120, validators=[userPortal.models.validate_minutes_left]),
        ),
    ]
