# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortal', '0006_remove_child_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='screentime_is_on',
            field=models.BooleanField(default=False),
        ),
    ]
