# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortal', '0009_child_daily_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='most_recent_screentime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
