# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortal', '0011_auto_20160823_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='no_screens_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
