# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userPortal', '0015_dailyrequirementsreport_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='did_do_homework',
        ),
        migrations.RemoveField(
            model_name='child',
            name='did_read',
        ),
    ]
