# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortal', '0018_auto_20160826_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='weekly_allowance',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dailyrequirementsreport',
            name='book_read',
            field=models.CharField(max_length=50, verbose_name="Today's book"),
        ),
        migrations.AlterField(
            model_name='dailyrequirementsreport',
            name='had_other_homework',
            field=models.BooleanField(verbose_name='Did self-directed study'),
        ),
        migrations.AlterField(
            model_name='dailyrequirementsreport',
            name='had_schoolwork',
            field=models.BooleanField(verbose_name='Did assigned schoolwork'),
        ),
        migrations.AlterField(
            model_name='dailyrequirementsreport',
            name='ixl_language_arts_completed',
            field=models.IntegerField(verbose_name='# IXL language arts skills today'),
        ),
        migrations.AlterField(
            model_name='dailyrequirementsreport',
            name='ixl_math_completed',
            field=models.IntegerField(verbose_name='Number of IXL math skills today'),
        ),
        migrations.AlterField(
            model_name='dailyrequirementsreport',
            name='reading_summary',
            field=models.CharField(max_length=100, verbose_name='Reading summary'),
        ),
    ]
