# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortal', '0019_auto_20160826_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='child_last_login',
            field=models.DateField(blank=True, null=True),
        ),
    ]
