# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortal', '0021_auto_20160829_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateevent',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
