# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userPortal', '0023_auto_20160830_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyrequirementsreport',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
