# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortal', '0025_auto_20160901_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrequirementsreport',
            name='homework_description',
            field=models.CharField(max_length=300, verbose_name='Homework summary'),
        ),
        migrations.AlterField(
            model_name='dailyrequirementsreport',
            name='reading_summary',
            field=models.CharField(max_length=300, verbose_name='Reading summary'),
        ),
    ]
