# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0002_store_item_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_item_request',
            name='date_of_request',
            field=models.DateField(blank=True, null=True),
        ),
    ]
